### PR TITLE
Add German translation

### PR DESCRIPTION
**Pull request by gglnx**
This adds a German translation and enables all strings used in JS to be translated.

### CODE REVIEW

**Comment by pvldigital** [comment]
Hi @gglnx,

I'll make a release for this after my Craft 3.4 update.

**Comment by gglnx** [comment]
Thank you! :)

**Comment by gglnx** [comment]
@pvldigital I think my pull request targeted the wrong the branch. It's not in master and therefore not released.

**Comment by pvldigital** [comment]
@gglnx yeah it's currently in the dev branch. I'll make a release for this after implementing some fixes. Will most likely go out in v2.6.2

**Pull request merged**
